CREATE DATABASE IF NOT EXISTS dm CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE reg_db (
  id          INT(3)      NOT NULL AUTO_INCREMENT,
  type        VARCHAR(30) NOT NULL,
  name        VARCHAR(30) NOT NULL,
  db_info     TEXT        NOT NULL,
  created_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_at  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);